import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';
import { log } from './logger';
import { detectAntigravityPath } from './validator';

export interface ProxyConfig {
    host: string;
    port: number;
    type: string;
    timeout: number;
    antigravityAppPath: string;
    autoStart: boolean;
}

const CONFIG_SECTION = 'antigravity-proxy';

/**
 * 从 VS Code settings 读取完整配置
 */
export function getConfig(): ProxyConfig {
    const cfg = vscode.workspace.getConfiguration(CONFIG_SECTION);

    let appPath = cfg.get<string>('antigravityAppPath', '');
    if (!appPath) {
        appPath = detectAntigravityPath() || '';
    }

    return {
        host: cfg.get<string>('proxyHost', '127.0.0.1'),
        port: cfg.get<number>('proxyPort', 10808),
        type: cfg.get<string>('proxyType', 'socks5'),
        timeout: cfg.get<number>('timeout', 5000),
        antigravityAppPath: appPath,
        autoStart: cfg.get<boolean>('autoStart', false),
    };
}

/**
 * 将配置写回 VS Code settings
 */
export async function updateConfig(config: Partial<ProxyConfig>): Promise<void> {
    const cfg = vscode.workspace.getConfiguration(CONFIG_SECTION);

    if (config.host !== undefined) {
        await cfg.update('proxyHost', config.host, vscode.ConfigurationTarget.Global);
    }
    if (config.port !== undefined) {
        await cfg.update('proxyPort', config.port, vscode.ConfigurationTarget.Global);
    }
    if (config.type !== undefined) {
        await cfg.update('proxyType', config.type, vscode.ConfigurationTarget.Global);
    }
    if (config.timeout !== undefined) {
        await cfg.update('timeout', config.timeout, vscode.ConfigurationTarget.Global);
    }

    if (config.antigravityAppPath !== undefined) {
        await cfg.update('antigravityAppPath', config.antigravityAppPath, vscode.ConfigurationTarget.Global);
    }
    if (config.autoStart !== undefined) {
        await cfg.update('autoStart', config.autoStart, vscode.ConfigurationTarget.Global);
    }

    log('配置已更新到 VS Code settings');
}

/**
 * 根据当前配置生成 config.yaml 文件
 */
export function syncConfigYaml(config: ProxyConfig): string {
    const content = `# Antigravity-Proxy Configuration (auto-generated by extension)
proxy:
  host: "${config.host}"
  port: ${config.port}
  type: "${config.type}"
  timeout: ${config.timeout}
  child_injection: true

# FakeIP range
dns:
  fakeip_range: "198.18.0.0/16"
`;

    // 始终使用临时目录作为 config.yaml 的存储位置
    const yamlPath = path.join('/tmp', 'antigravity-config.yaml');

    fs.writeFileSync(yamlPath, content, 'utf-8');
    log(`config.yaml 已同步到 ${yamlPath}`);
    return yamlPath;
}

/**
 * 检查配置是否完整可用
 */
export function isConfigComplete(config: ProxyConfig): boolean {
    // 现在不再强制要求 projectPath，因为有内置二进制
    return !!(config.host && config.port);
}
